### ISSUE TITLE
springboot letsencrypt 인증서 적용 방법

### ISSUE THREAD

**Issue by lkh5510** [lkh4768/blog#1]
springboot letsencrypt 인증서 적용 방법

**Comment by lkh4768** [comment]
http://sw-warehouse.xyz/2018/06/21/springboot%EC%97%90-letsencrypt%EB%A1%9C-%EB%A7%8C%EB%93%A0-%EC%9D%B8%EC%A6%9D%EC%84%9C-%EC%A0%81%EC%9A%A9/
